name: Native Repair V21
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'zulu' }
      - name: Build with Gradle
        run: |
          echo "sdk.dir=/usr/lib/android-sdk" > local.properties
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/BT-NATIVE-V21.apk
      - uses: actions/upload-artifact@v4
        with: { name: BT-NATIVE-V21, path: app/build/outputs/apk/debug/BT-NATIVE-V21.apk }